name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests


      # Step 5: Run a basic test to check for execution errors
      - name: Run Basic Test
        run: |
          python -m tkinter || echo "Tkinter is not available in this environment"
          python -c "import requests"

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()  # Only run deployment if tests pass

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyinstaller

      # Step 4: Build executable with PyInstaller
      - name: Build Executable
        run: |
          pyinstaller --onefile --windowed graphhopper_parse-json_9.py

      # Step 5: Upload Artifact (Executable)
      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: project_activity3_executable
          path: grapphopper_parse-json_9.exe

    