name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment (Python 3.9 in this case)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r https://github.com/Andre-Roble/Group-Act-4/tree/main/sys-integ-grp-act-4-main/requirements.txt

      # Step 4: Run the Python script
      - name: Run Python Script
        run: python https://github.com/Andre-Roble/Group-Act-4/blob/main/sys-integ-grp-act-4-main/graphhopper_parse-json_9.py


